name: Pull Request - Auto Assign BC Gov Internal Developers and Government Contractors

on:
  pull_request:
    types: [ opened, reopened]
jobs:
  assign-team-members:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Teams
        uses: delivery-much/actions-assigner@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          team-reviewers: bcgov-cirmo-dpia, contractor-cirmo-dpia
